reviews:
  profile: assertive
  auto_review:
    enabled: false
    # base_branches:
  tools:
    yamllint:
      enabled: false
    ansible-lint:
      enabled: false
  reviews:
    high_level_summary: true
